name: Continuous Integration
# runs the jobs below when 1) opening / updating a pull request 2) merging a feature branch into main

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker image and run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from Github
        uses: actions/checkout@v3
      - name: Run end-to-end tests # runs compose & builds the images, and stops all containers when the test-service terminates
        run: >
          docker compose --profile testing up
          --build
          --exit-code-from test-service
        